version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            - DJANGO_SU_NAME=toast
            - DJANGO_SU_EMAIL=toast@nhntoast.com
            - DJANGO_SU_PASSWORD=test1234
        volumes:
            - .:/django_server
        expose:
            - "4000"
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/django_server
            - ./config/nginx/:/etc/nginx/conf.d/
        depends_on:
            - web
